apiVersion: v1
data:
  kubectl.kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: XXX
        server: https://1.1.1.1:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: admin
      name: kubernetes
    current-context: kubernetes
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: XXX
        client-key-data: XXX
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-19T02:41:22Z"
  name: k8s-configmap
  namespace: default
  resourceVersion: "14177838"
  selfLink: /api/v1/namespaces/default/configmaps/k8s-configmap
  uid: 95eb6418-b97f-4153-8dac-4a279192f2b1
